version: "3"
services:
  frontend:
    image: pskreter/frontend:${IMAGE_VERSION}
    environment:
      - JAEGER_COLLECTION_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_AGENT_ENDPOINT=http://jaeger:6831
    ports:
      - "8081:8081"
  customers:
    image: pskreter/customers:${IMAGE_VERSION}
    environment:
      - JAEGER_COLLECTION_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_AGENT_ENDPOINT=http://jaeger:6831
    ports:
      - "8082:8082"
  jaeger:
    image: jaegertracing/all-in-one:1.8
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
